version: '3.8'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./projects:/var/www/html
    depends_on:
      - php
      - golang
    networks:
      - dev-net

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php
    volumes:
      - ./projects:/var/www/html
    networks:
      - dev-net

  golang:
    build:
      context: ./services/golang
      args:
        GO_VERSION: ${GO_VERSION}
    container_name: golang
    volumes:
      - ./projects:/go/src
    networks:
      - dev-net

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - dev-net

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - dev-net

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge
